name: prometheus-apt-exporter
version: '0.2.5'
grade: stable
summary: Export textfile-based apt-repositories metrics from parsed log data
description: >
    This project provides an textfile-based exporter for apt-repositories.
confinement: strict
license: GPL-3.0
base: core20

plugs:
  apt-exporter-files:
    interface: system-files
    read:
      - /usr/share/dpkg
      - /etc/apt/apt.conf.d
      - /var/lib/snapd/hostfs/etc/apt
      - /var/lib/snapd/hostfs/var/cache/apt
      - /var/lib/snapd/hostfs/var/cache/apt/srcpkgcache.bin
      - /var/lib/snapd/hostfs/var/lib/apt
      - /var/lib/snapd/hostfs/var/lib/dpkg
      - /var/lib/snapd/hostfs/var/lib/dpkg/status
      - /var/lib/snapd/hostfs/usr/bin/dpkg
      - /var/lib/snapd/hostfs/usr/share/dpkg/cputable
      - /var/lib/snapd/hostfs/etc/apt/apt.conf.d
      - /var/lib/snapd/hostfs/etc/apt/sources.list
      - /var/lib/snapd/hostfs/etc/apt/sources.list.d
    write:
      - /var/lib/snapd/hostfs/var/cache/apt

apps:
  apt-exporter:
    command: 'bin/pkg-exporter --rootdir /var/lib/snapd/hostfs/ -d'
    daemon: simple
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - apt-exporter-files
      - network-bind

parts:
  pkg-exporter:
    plugin: python
    source: https://github.com/helgharbi/pkg-exporter.git
    stage-packages:
      - python3-apt
