name: prometheus-apt-exporter
version: '1.0.1'
grade: stable
summary: Export textfile-based apt-repositories metrics from parsed log data
description: >
    This project provides an textfile-based exporter for apt-repositories.
confinement: strict
license: GPL-3.0
base: core20
architectures:
  - build-on: amd64

layout:
  /etc/apt:
    bind: $SNAP_DATA/etc/apt

apps:
  apt-exporter:
    command: 'bin/set_apt_cache_env.sh'
    daemon: simple
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - system-backup
      - network-bind

parts:
  pkg-exporter:
    plugin: python
    source: https://github.com/helgharbi/pkg-exporter.git
    stage-packages:
      - python3-apt
      - dpkg
  set-apt-cache-config:
    plugin: dump
    source: bin
    organize:
      set_apt_cache_env.sh: bin/set_apt_cache_env.sh
